export const saga_action_ids = {
	ADD_REMINDER: "ADD_REMINDER",
	UPDATE_REMINDER: "UPDATE_REMINDER",
	DELETE_REMINDER: "DELETE_REMINDER"
}

export const saga_actions_types = {
	REMINDER_ADDED: "REMINDER_ADDED",
	GET_REMINDERS: "GET_REMINDERS",
	REMINDER_COMPLETED: "REMINDER_COMPLETED",
	REMINDER_UPDATED: "REMINDER_UPDATED",
	REMINDER_DELETE: "REMINDER_DELETE",

}